---
- hosts: node0
  become: yes
  vars:
    files:
      - /home/app/faceapp/face-api/Containerfile
      - /home/app/faceapp/face-web/Containerfile
  tasks:
    - name: create app user
      user:
        name: app
        groups: wheel
        state: present
        # encrypted pass is "pass"
        # openssl passwd -1 pass
        password: $1$9IxS4KfB$gNV0GShx5ue6.eSzDNqu./
    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
    - name: check that pip3 available
      shell: which pip3
      register: pip_installed
    - name: install podman-compose
      shell: pip3 install podman-compose
      when: pip_installed.rc == 0
    - name: start & enable cockpit and firewalld service
      block:
        - service:
            name: "{{ item }}"
            state: started
            enabled: yes
          loop: "{{ services }}"
        - debug: msg="services available"
      rescue:
        - debug: msg="Something when wrong"
      always:
        - debug: msg="Attempt completed"
    - name: open ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ port_list }}"
      notify: restart firewalld
    - name: check if repo already cloned
      shell: ls /home/app/faceapp
      register: check_repo
      ignore_errors: yes
    - name: clone repo
      git:
        repo: https://github.com/abdilmajid/faceapp.git
        dest: /home/app/faceapp
      when: check_repo.rc != 0
    - name: store public ip address in variable "pub_ip"
      shell: grep node0 /etc/hosts | cut -f1 -d' '
      register: pub_ip
    - name: update Containerfiles
      replace:
        path: "{{ item }}"
        regexp: '192.168.50.5'
        replace: "{{ pub_ip.stdout }}"
      loop: "{{ files }}"
    - name: update Containerfiles
      replace:
        path: "{{ item }}"
        regexp: '192.168.50.5'
        replace: "{{ ansible_default_ipv4.address }}"
      loop: "{{ files }}"
    - name: check dir ownership
      shell: ls -la|grep faceapp |awk '{print $3}'
      register: dir_owner
    - name: update owner  
      shell: sudo chown -R app:app /home/app/faceapp
      when: dir_owner.stdout != "app"
    - name: check folder context
      shell: ls -laZ /home/app/faceapp | grep container_file_t
      register: dir_context
      ignore_errors: yes
    - name: update context type
      shell: sudo semanage fcontext -a -t container_file_t "/home/app/faceapp(/.*)?"
      ignore_errors: yes
      when: dir_context.rc != 0
    - name: context changed
      shell: sudo restorecon -R -v /home/app/faceapp
      when: dir_context.rc != 0
    - name: check linger status
      shell: sudo loginctl show-user app | grep Linger | cut -f1 -d'='
      register: linger_check
    - name: enable linger
      shell: sudo loginctl enable-linger app
      when: linger_check.stdout != "yes"


  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: reloaded
...